from __future__ import annotations

SESSION_AUTO_COMPACTION_CONTEXT_WINDOW_UTILIZATION = 0.7
SESSION_AUTO_COMPACTION_PROMPT_RESERVE_TOKENS = 24_000
SESSION_COMPACTION_CONTEXT_WINDOW_UTILIZATION = 0.8
SESSION_COMPACTION_CHARS_PER_TOKEN_HEURISTIC = 4
DEFAULT_SESSION_COMPACTION_SOURCE_CHAR_LIMIT = 120_000
MAX_COMPACTION_TEXT_FIELD_CHARS = 1_200
MAX_COMPACTION_TOOL_ACTIVITY_LINES = 8


__all__ = [
    "DEFAULT_SESSION_COMPACTION_SOURCE_CHAR_LIMIT",
    "MAX_COMPACTION_TEXT_FIELD_CHARS",
    "MAX_COMPACTION_TOOL_ACTIVITY_LINES",
    "SESSION_AUTO_COMPACTION_CONTEXT_WINDOW_UTILIZATION",
    "SESSION_AUTO_COMPACTION_PROMPT_RESERVE_TOKENS",
    "SESSION_COMPACTION_CHARS_PER_TOKEN_HEURISTIC",
    "SESSION_COMPACTION_CONTEXT_WINDOW_UTILIZATION",
]
